// Industry options for dropdown selection
export const industryCardOptions = [
  { value: "Chemicals", label: "Chemicals" },
  { value: "Metals and Mining", label: "Metals and Mining" },
  { value: "Automobiles, Two Wheelers and Other Private Transportation", label: "Automobiles, Two Wheelers and Other Private Transportation" },
  { value: "Public and Goods Transportation", label: "Public and Goods Transportation" },
  { value: "Houseware and Household Goods", label: "Houseware and Household Goods" },
  { value: "Media and Entertainment", label: "Media and Entertainment" },
  { value: "Travelling, Tourism, and Hospitality", label: "Travelling, Tourism, and Hospitality" },
  { value: "Electronics", label: "Electronics" },
  { value: "Food, Beverages, Tobacco, and Other Consumables", label: "Food, Beverages, Tobacco, and Other Consumables" },
  { value: "Healthcare and Medicine", label: "Healthcare and Medicine" },
  { value: "Energy", label: "Energy" },
  { value: "Finance", label: "Finance" },
  { value: "Aerospace and Aviation", label: "Aerospace and Aviation" },
  { value: "Defence", label: "Defence" },
  { value: "Construction and Materials", label: "Construction and Materials" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "General Industrial Equipment, Engineering and Services", label: "General Industrial Equipment, Engineering and Services" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Telecommunication Services and Equipment", label: "Telecommunication Services and Equipment" },
  { value: "Software Services, Apps, and Equipment", label: "Software Services, Apps, and Equipment" },
  { value: "Public Utilities", label: "Public Utilities" },
  { value: "Agriculture, Fishing, Animal Husbandry", label: "Agriculture, Fishing, Animal Husbandry" },
  { value: "Physical Labour", label: "Physical Labour" },
  { value: "General Management", label: "General Management" },
  { value: "Sales and Marketing", label: "Sales and Marketing" },
  { value: "Law", label: "Law" },
  { value: "Artistic, Technical, and Other Professional Services", label: "Artistic, Technical, and Other Professional Services" },
  { value: "Social Services and Environmentalism", label: "Social Services and Environmentalism" },
  { value: "Education and Academia", label: "Education and Academia" },
  { value: "Retail", label: "Retail" },
  { value: "Other Industry", label: "Other Industry" },
];

// Skill options for dropdown selection
export const skillCardOptions = [
  { value: "Physics", label: "Physics" },
  { value: "Chemistry", label: "Chemistry" },
  { value: "Biology", label: "Biology" },
  { value: "Astrophysics and Astronomy", label: "Astrophysics and Astronomy" },
  { value: "Geoscience", label: "Geoscience" },
  { value: "Other Science", label: "Other Sciences" },
  { value: "Computer and Software Engineering", label: "Computer and Software Engineering" },
  { value: "Electronics Engineering", label: "Electronics Engineering" },
  { value: "Electrical Engineering", label: "Electrical Engineering" },
  { value: "Mechanical Engineering", label: "Mechanical Engineering" },
  { value: "Chemical Engineering", label: "Chemical Engineering" },
  { value: "Civil Engineering", label: "Civil Engineering" },
  { value: "Biomedical Engineering", label: "Biomedical Engineering" },
  { value: "Other Engineering", label: "Other Engineering" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Architecture", label: "Architecture" },
  { value: "Painting", label: "Painting" },
  { value: "Photography", label: "Photography" },
  { value: "Sculpting", label: "Sculpting" },
  { value: "Music", label: "Music" },
  { value: "Film", label: "Film" },
  { value: "Fashion", label: "Fashion" },
  { value: "Literary Arts", label: "Literary Arts" },
  { value: "Mixed Media Arts", label: "Mixed Media Arts" },
  { value: "Animator", label: "Animator" },
  { value: "Designer", label: "Designer" },
  { value: "Video Games", label: "Video Games" },
  { value: "Other Fine Arts", label: "Other Fine Arts" },
  { value: "Sociology", label: "Sociology" },
  { value: "Psychology", label: "Psychology" },
  { value: "Journalism", label: "Journalism" },
  { value: "History", label: "History" },
  { value: "Geography", label: "Geography" },
  { value: "Economics", label: "Economics" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "Other Arts", label: "Other Arts" },
  { value: "Finance and Insurance", label: "Finance and Insurance" },
  { value: "General Management", label: "General Management" },
  { value: "Law", label: "Law" },
  { value: "Academia and Education", label: "Academia and Education" },
  { value: "Hospitality", label: "Hospitality" },
  { value: "Healthcare and Medicine", label: "Healthcare and Medicine" },
  { value: "Consultancy Services", label: "Consultancy Services" },
  { value: "Brokerage Services", label: "Brokerage Services" },
  { value: "Event Management Services", label: "Event Management Services" },
  { value: "Training Services", label: "Training Services" },
  { value: "Human Resource Management Services", label: "Human Resource Management Services" },
  { value: "Research Services", label: "Research Services" },
  { value: "Other Services", label: "Other Services" },
  { value: "Entrepreneurs and Self Owned Businesses", label: "Entrepreneurs and Self Owned Businesses" },
  { value: "Accountancy", label: "Accountancy" },
  { value: "Social Services, Environmentalism and Not for Profit Work", label: "Social Services, Environmentalism and Not for Profit Work" },
  { value: "Other Skills", label: "Other Skills" },
];

const options = { industryCardOptions, skillCardOptions };
export default options;
