// Industry options — top-level categories from Industry Cards document
export const industryCardOptions = [
  { value: "Chemicals", label: "Chemicals" },
  { value: "Metals and Mining", label: "Metals and Mining" },
  { value: "Automobiles and Private Transportation", label: "Automobiles and Private Transportation" },
  { value: "Public Transportation", label: "Public Transportation" },
  { value: "Media and Entertainment", label: "Media and Entertainment" },
  { value: "Travel, Tourism, and Hospitality", label: "Travel, Tourism, and Hospitality" },
  { value: "Household Goods and Appliances", label: "Household Goods and Appliances" },
  { value: "Consumer Electronics", label: "Consumer Electronics" },
  { value: "Food, Beverage, Tobacco, and Consumables", label: "Food, Beverage, Tobacco, and Consumables" },
  { value: "Healthcare and Life Sciences", label: "Healthcare and Life Sciences" },
  { value: "Energy", label: "Energy" },
  { value: "Finance", label: "Finance" },
  { value: "Aerospace and Aviation", label: "Aerospace and Aviation" },
  { value: "Defence and Security", label: "Defence and Security" },
  { value: "Construction and Building Materials", label: "Construction and Building Materials" },
  { value: "Manufacturing (General)", label: "Manufacturing (General)" },
  { value: "Industrial Equipment and Services", label: "Industrial Equipment and Services" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Software and Technology", label: "Software and Technology" },
  { value: "Utilities", label: "Utilities" },
  { value: "Agriculture and Natural Resources", label: "Agriculture and Natural Resources" },
  { value: "Labour and Workforce", label: "Labour and Workforce" },
  { value: "Corporate and Management Services", label: "Corporate and Management Services" },
  { value: "Sales and Marketing", label: "Sales and Marketing" },
  { value: "Professional Services", label: "Professional Services" },
  { value: "Environmental and Social Impact", label: "Environmental and Social Impact" },
  { value: "Education and Academia", label: "Education and Academia" },
  { value: "Retail and Commerce", label: "Retail and Commerce" },
  { value: "Logistics and Supply Chain", label: "Logistics and Supply Chain" },
  { value: "Textiles and Apparel", label: "Textiles and Apparel" },
  { value: "Sports Industry", label: "Sports Industry" },
  { value: "Religious and Cultural Institutions", label: "Religious and Cultural Institutions" },
  { value: "Government and Public Administration", label: "Government and Public Administration" },
  { value: "Research and Development", label: "Research and Development" },
  { value: "Security and Risk Management", label: "Security and Risk Management" },
  { value: "Space Economy", label: "Space Economy" },
  { value: "Creator Economy", label: "Creator Economy" },
  { value: "Pet Industry", label: "Pet Industry" },
  { value: "Luxury Industry", label: "Luxury Industry" },
];

// Skill options — top-level categories from Skill Card document
export const skillCardOptions = [
  { value: "Sciences", label: "Sciences" },
  { value: "Engineering and Technology", label: "Engineering and Technology" },
  { value: "Mathematics and Quantitative Skills", label: "Mathematics and Quantitative Skills" },
  { value: "Architecture and Built Environment", label: "Architecture and Built Environment" },
  { value: "Creative and Artistic Skills", label: "Creative and Artistic Skills" },
  { value: "Humanities and Social Sciences", label: "Humanities and Social Sciences" },
  { value: "Business and Economic Skills", label: "Business and Economic Skills" },
  { value: "Legal and Governance Skills", label: "Legal and Governance Skills" },
  { value: "Education and Knowledge Transfer", label: "Education and Knowledge Transfer" },
  { value: "Healthcare and Medicine", label: "Healthcare and Medicine" },
  { value: "Hospitality and Tourism", label: "Hospitality and Tourism" },
  { value: "Service Sector Skills", label: "Service Sector Skills" },
  { value: "Social Impact and Public Sector", label: "Social Impact and Public Sector" },
  { value: "Communication Skills", label: "Communication Skills" },
  { value: "Leadership and Organizational Skills", label: "Leadership and Organizational Skills" },
  { value: "Physical and Performance Skills", label: "Physical and Performance Skills" },
  { value: "Skilled Trades and Crafts", label: "Skilled Trades and Crafts" },
  { value: "Agriculture and Natural Resource Skills", label: "Agriculture and Natural Resource Skills" },
  { value: "Logistics and Operations", label: "Logistics and Operations" },
  { value: "Personal and Cognitive Skills", label: "Personal and Cognitive Skills" },
  { value: "Digital Economy Skills", label: "Digital Economy Skills" },
  { value: "Political and Diplomatic Skills", label: "Political and Diplomatic Skills" },
  { value: "Religious and Spiritual Skills", label: "Religious and Spiritual Skills" },
  { value: "Survival and Field Skills", label: "Survival and Field Skills" },
];

const options = { industryCardOptions, skillCardOptions };
export default options;
