import type { BadgeDef } from "./ventureConstants";

export type StageBadgeTemplate = "venture" | "academic" | "lab" | "creative";
export type StageBadgeKind = "A" | "B" | "C";

export type StageBadgeDef = BadgeDef & {
  template: StageBadgeTemplate;
  stage: number;
  badgeType: StageBadgeKind;
};

const rows: Array<[
  number,
  string,
  StageBadgeTemplate,
  number,
  StageBadgeKind,
  BadgeDef["rarity"],
  string,
  string,
  string,
  string,
  string,
  string,
]> = [
  [101, "The Problem Named", "venture", 1, "A", "common", "spark", "#FEF9C3", "#CA8A04", "A single lit match held upright against a dark background - the smallest possible flame", "You saw it clearly enough to say it out loud.", "Complete Task 1 of Checkpoint 1 in Stage 1 (Ideation) - describe the problem in a short statement"],
  [102, "The Spark Struck", "venture", 1, "B", "common", "ribbon", "#EEF2FF", "#4F46E5", "A ribbon badge with a small flame at its centre and a checkmark at the base", "The first fire lit. The question that would not go away.", "Complete Stage 1 (Ideation) on any Venture idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [103, "The Ideation Mastered", "venture", 1, "C", "uncommon", "crown", "#FDE68A", "#92400E", "A small crown resting on a flame - mastery at the very start of the journey", "Not just a spark. Every task completed. Every question answered.", "Complete Stage 1 (Ideation) on any Venture idea with all 3 tasks completed at every checkpoint (full gold path)"],
  [104, "The Landscape Glimpsed", "venture", 2, "A", "common", "compass", "#F0FDF4", "#059669", "A compass needle pointing toward an unlabelled horizon - direction without full knowledge yet", "A market named is a market half understood.", "Complete Task 1 of Checkpoint 1 in Stage 2 (Research) - write a summary of the market"],
  [105, "The Map Drawn", "venture", 2, "B", "common", "scroll", "#ECFDF5", "#059669", "A partially unrolled scroll showing a hand-drawn map with rough terrain markings", "You did not guess at the terrain. You went and looked.", "Complete Stage 2 (Research) on any Venture idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [106, "The Research Exhausted", "venture", 2, "C", "uncommon", "tome", "#FDE68A", "#92400E", "A thick open book with every page filled - a complete record of what was found", "Every source followed. Every assumption tested. Nothing left to chance.", "Complete Stage 2 (Research) with all 3 tasks completed at every checkpoint"],
  [107, "The Reckoning Begun", "venture", 3, "A", "common", "scale", "#FFF7ED", "#B45309", "A single pan of a balance scale, empty - waiting to be weighed", "The beliefs you wrote down are the ones you can test.", "Complete Task 1 of Checkpoint 1 in Stage 3 (Validation) - list at least eight assumptions your idea relies on"],
  [108, "The World Answered", "venture", 3, "B", "uncommon", "shield", "#FCE7F3", "#9D174D", "A shield with a checkmark and a small speech bubble at its centre - the world has spoken", "You asked. The evidence replied. You listened.", "Complete Stage 3 (Validation) on any Venture idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [109, "The Assumption Slain", "venture", 3, "C", "rare", "sword", "#FDE68A", "#92400E", "A sword planted upright in a stone - the battle against assumption fully fought", "Every belief challenged. Every result uploaded. The idea survived honesty.", "Complete Stage 3 (Validation) with all 3 tasks completed at every checkpoint"],
  [110, "The Journey Charted", "venture", 4, "A", "common", "map_pin", "#EEF2FF", "#4F46E5", "A single map pin dropped onto a winding path - the start of mapping the customer route", "You described the path before you asked anyone to walk it.", "Complete Task 1 of Checkpoint 1 in Stage 4 (Offer Design) - describe the core customer journey in five to eight steps"],
  [111, "The Shape of Things", "venture", 4, "B", "uncommon", "diamond", "#EEEDFE", "#7F77DD", "A geometric diamond shape with clean edges - something formless that now has definition", "What was formless now has edges. What was imagined now has a price.", "Complete Stage 4 (Offer Design) on any Venture idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [112, "The Offer Perfected", "venture", 4, "C", "rare", "gem", "#FDE68A", "#92400E", "A cut gemstone - every facet deliberate, every angle refined", "Tested, revised, finalised. Nothing left undefined.", "Complete Stage 4 (Offer Design) with all 3 tasks completed at every checkpoint"],
  [113, "The Engine Described", "venture", 5, "A", "common", "cog", "#F0FDF4", "#059669", "A single cog with an arrow passing through it - the mechanism named before it runs", "The machine does not run until someone writes down how it works.", "Complete Task 1 of Checkpoint 1 in Stage 5 (Build & Deliver) - write a short operations brief"],
  [114, "The Forge Emptied", "venture", 5, "B", "rare", "anvil", "#FCE7F3", "#9D174D", "An anvil with no work remaining on it - everything made, the forge finally quiet", "Everything made. Everything ready. The work of the hands is done.", "Complete Stage 5 (Build & Deliver) on any Venture idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [115, "The Build Complete", "venture", 5, "C", "epic", "monument", "#FDE68A", "#92400E", "A small monument - a structure built entirely from effort, standing without support", "Every system built. Every pilot run. Every issue logged and resolved.", "Complete Stage 5 (Build & Deliver) with all 3 tasks completed at every checkpoint"],
  [116, "The Signal Prepared", "venture", 6, "A", "common", "flag", "#FFF7ED", "#B45309", "A folded flag, not yet raised - ready but not yet flown", "Before you can be found, you must say what you are.", "Complete Task 1 of Checkpoint 1 in Stage 6 (Launch) - write the core launch message"],
  [117, "The Harbour Left", "venture", 6, "B", "rare", "ship", "#FEF3C7", "#92400E", "A ship leaving a harbour at dawn, sails catching wind - the shore already behind it", "The sails caught wind. The shore disappeared. The venture is real.", "Complete Stage 6 (Launch) on any Venture idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [118, "The Full Launch", "venture", 6, "C", "epic", "rocket", "#FDE68A", "#92400E", "A rocket fully clear of the launchpad with a complete trail below - nothing held back", "Every channel documented. Every customer attributed. Every asset live.", "Complete Stage 6 (Launch) with all 3 tasks completed at every checkpoint"],
  [119, "The Voices Gathered", "venture", 7, "A", "common", "ear", "#EEF2FF", "#4F46E5", "A stylised ear with several small speech bubbles floating toward it - listening in progress", "What the market said is only useful if someone wrote it down.", "Complete Task 1 of Checkpoint 1 in Stage 7 (Iteration) - write a summary of post-launch feedback"],
  [120, "The Second Shaping", "venture", 7, "B", "uncommon", "chisel", "#EEEDFE", "#7F77DD", "A chisel and a block - the second pass of the tool across something already built", "The first version was a question. This one is an answer.", "Complete Stage 7 (Iteration) on any Venture idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [121, "The Loop Closed", "venture", 7, "C", "rare", "ring", "#FDE68A", "#92400E", "A complete ring with a small arrow showing the direction of travel - the feedback loop completed", "Feedback gathered, priorities set, changes delivered, impact measured.", "Complete Stage 7 (Iteration) with all 3 tasks completed at every checkpoint"],
  [122, "The Roads Identified", "venture", 8, "A", "common", "crossroads", "#F0FDF4", "#059669", "Four roads meeting at a junction - multiple paths forward, none yet chosen", "Growth that cannot be named cannot be repeated.", "Complete Task 1 of Checkpoint 1 in Stage 8 (Scale) - describe at least four acquisition channels"],
  [123, "The Kingdom Grows", "venture", 8, "B", "rare", "castle", "#FCE7F3", "#9D174D", "A small castle with a new wing being added - growth visible in the structure itself", "You did not build a business. You built a thing that builds itself.", "Complete Stage 8 (Scale) on any Venture idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [124, "The Venture Scaled", "venture", 8, "C", "epic", "crown", "#FDE68A", "#92400E", "A crown placed on a map - sovereignty over a territory that now runs itself", "Every channel tested. Every bottleneck resolved. Every partnership signed.", "Complete Stage 8 (Scale) with all 3 tasks completed at every checkpoint"],
  [125, "The Field Entered", "academic", 1, "A", "common", "door", "#F0FDF4", "#059669", "An open doorway with light beyond - the threshold into a new intellectual territory", "Every inquiry begins by naming the territory it will cross.", "Complete Task 1 of Checkpoint 1 in Stage 1 (Topic & Question) - write a paragraph describing your area of interest"],
  [126, "The Question Formed", "academic", 1, "B", "common", "lantern", "#ECFDF5", "#059669", "A lantern held up in a dark space - illuminating the question without yet answering it", "A question precise enough to answer is already half an answer.", "Complete Stage 1 (Topic & Question) on any Academic idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [127, "The Question Sharpened", "academic", 1, "C", "uncommon", "quill", "#FDE68A", "#92400E", "A quill with a very fine point - precision as an act of craft", "Researchable. Specific. Open. The question earned its right to be asked.", "Complete Stage 1 (Topic & Question) with all 3 tasks completed at every checkpoint"],
  [128, "The Hunt Begun", "academic", 2, "A", "common", "compass", "#EEF2FF", "#4F46E5", "A compass and a blank map - the search has a direction but not yet a destination", "A search without a plan finds everything except what matters.", "Complete Task 1 of Checkpoint 1 in Stage 2 (Literature Review) - list key search terms from your research question"],
  [129, "The Conversation Heard", "academic", 2, "B", "common", "scroll", "#ECFDF5", "#059669", "An open scroll with many names and references - the record of a long conversation", "You read what others said before deciding what you would add.", "Complete Stage 2 (Literature Review) on any Academic idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [130, "The Literature Mapped", "academic", 2, "C", "rare", "web", "#FDE68A", "#92400E", "A web of connected nodes - sources linked to each other by argument and theme", "Every source evaluated. Every theme charted. Every gap named.", "Complete Stage 2 (Literature Review) with all 3 tasks completed at every checkpoint"],
  [131, "The Direction Set", "academic", 3, "A", "common", "arrow", "#FFF7ED", "#B45309", "A single arrow pointing forward - direction chosen, not yet distance covered", "To name your approach is to commit to a kind of truth.", "Complete Task 1 of Checkpoint 1 in Stage 3 (Methodology) - state your methodological approach in two sentences"],
  [132, "The Method Chosen", "academic", 3, "B", "uncommon", "blueprint", "#EEEDFE", "#7F77DD", "A rolled blueprint with a seal - a plan complete enough to be authoritative", "The tool was selected for the work, not the work for the tool.", "Complete Stage 3 (Methodology) on any Academic idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [133, "The Method Defended", "academic", 3, "C", "rare", "shield", "#FDE68A", "#92400E", "A shield with a blueprint pattern - the method protected against challenge", "The approach was argued for, not just chosen. It can withstand scrutiny.", "Complete Stage 3 (Methodology) with all 3 tasks completed at every checkpoint"],
  [134, "The Architecture Drawn", "academic", 4, "A", "common", "blueprint", "#F0FDF4", "#059669", "A floor plan - the structure mapped before a single wall is built", "A building without a plan is rubble waiting to happen.", "Complete Task 1 of Checkpoint 1 in Stage 4 (Writing & Drafting) - write a section-by-section outline"],
  [135, "The Draft Stands", "academic", 4, "B", "uncommon", "tome", "#EEEDFE", "#7F77DD", "A thick closed book standing upright - complete enough to stand on its own", "The argument existed in your head. Now it exists in the world.", "Complete Stage 4 (Writing & Drafting) on any Academic idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [136, "The Draft Perfected", "academic", 4, "C", "epic", "crown_and_tome", "#FDE68A", "#92400E", "An open book with a crown above it - the full draft completed with distinction", "Every section drafted. Every peer review completed. The full argument stands.", "Complete Stage 4 (Writing & Drafting) with all 3 tasks completed at every checkpoint"],
  [137, "The Mirror Faced", "academic", 5, "A", "common", "mirror", "#FFF7ED", "#B45309", "A hand mirror held up - honest reflection before external review", "The hardest reviewer is always the one who knows exactly what you intended.", "Complete Task 1 of Checkpoint 1 in Stage 5 (Review & Revision) - list at least five specific things to improve"],
  [138, "The Work Remade", "academic", 5, "B", "uncommon", "chisel", "#ECFDF5", "#059669", "A chisel and a revised stone - the same shape, but better", "The first draft said what you meant. The revision says it better.", "Complete Stage 5 (Review & Revision) on any Academic idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [139, "The Piece Polished", "academic", 5, "C", "rare", "gem", "#FDE68A", "#92400E", "A gemstone after cutting - the same material, transformed by sustained attention", "Two readers. Every citation audited. Every sentence heard aloud.", "Complete Stage 5 (Review & Revision) with all 3 tasks completed at every checkpoint"],
  [140, "The Venue Weighed", "academic", 6, "A", "common", "scale", "#EEF2FF", "#4F46E5", "A balance scale with a scroll on one side - the work being assessed against the right home for it", "The right home for a piece of work is itself a judgment worth making.", "Complete Task 1 of Checkpoint 1 in Stage 6 (Submission & Publication) - describe at least three possible submission venues"],
  [141, "The Work Released", "academic", 6, "B", "rare", "open_gate", "#FCE7F3", "#9D174D", "An open gate with a scroll passing through it - the work leaving the hand of its creator", "It left your hands. It entered the record. That cannot be undone.", "Complete Stage 6 (Submission & Publication) on any Academic idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [142, "The Record Complete", "academic", 6, "C", "epic", "seal", "#FDE68A", "#92400E", "A wax seal on a closed scroll - the record sealed, the work complete and official", "Submitted. Reviewed. Revised. Confirmed. The full scholarly cycle completed.", "Complete Stage 6 (Submission & Publication) with all 3 tasks completed at every checkpoint"],
  [143, "The Work Described", "lab", 1, "A", "common", "notepad", "#FFF7ED", "#B45309", "A small notepad with two lines written on it - the minimum required to begin", "Two sentences. What you will do and what done looks like.", "Complete Task 1 of Checkpoint 1 in Stage 1 (Brief & Question) - describe what you are setting out to do in two to three sentences"],
  [144, "The Scope Defined", "lab", 1, "B", "common", "frame", "#FEF3C7", "#92400E", "A picture frame around an empty space - the boundaries set, the content not yet filled", "A Lab without edges is not a Lab. It is a wander.", "Complete Stage 1 (Brief & Question) on any Lab idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [145, "The Brief Mastered", "lab", 1, "C", "uncommon", "compass", "#FDE68A", "#92400E", "A compass with all four directions marked - complete orientation before the Lab begins", "The brief uploaded. The question tested. The hypothesis falsifiable.", "Complete Stage 1 (Brief & Question) with all 3 tasks completed at every checkpoint"],
  [146, "The Trail Found", "lab", 2, "A", "common", "footprints", "#F0FDF4", "#059669", "A set of footprints in soft ground - evidence that others have passed this way before", "Four sources that touched what you are about to touch.", "Complete Task 1 of Checkpoint 1 in Stage 2 (Research & Background) - list at least four relevant sources with a sentence on each"],
  [147, "The Ground Surveyed", "lab", 2, "B", "common", "map", "#ECFDF5", "#059669", "A surveyor's map with measurements marked - the territory understood before work begins", "You did not build on sand. You checked what was already there.", "Complete Stage 2 (Research & Background) on any Lab idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [148, "The Foundation Laid", "lab", 2, "C", "uncommon", "cornerstone", "#FDE68A", "#92400E", "A cornerstone being placed - the first solid element of what will be built on top", "Every method compared. Every resource confirmed. The Kanban ready before the build.", "Complete Stage 2 (Research & Background) with all 3 tasks completed at every checkpoint"],
  [149, "The Approach Chosen", "lab", 3, "A", "common", "fork_in_road", "#EEF2FF", "#4F46E5", "A fork in the road with one path clearly marked - the choice made and committed to", "To commit to a method is to trust your reasoning about the question.", "Complete Task 1 of Checkpoint 1 in Stage 3 (Design & Planning) - describe and justify your chosen approach"],
  [150, "The Procedure Written", "lab", 3, "B", "uncommon", "blueprint", "#EEEDFE", "#7F77DD", "A detailed blueprint with numbered steps - a plan complete enough for someone else to follow", "The plan is the promise the Lab makes to its own results.", "Complete Stage 3 (Design & Planning) on any Lab idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [151, "The Design Locked", "lab", 3, "C", "rare", "padlock", "#FDE68A", "#92400E", "A padlock on a blueprint - the design finalised and committed to", "Peer-reviewed procedure. Calendar mapped. Ethics confirmed. Nothing left open.", "Complete Stage 3 (Design & Planning) with all 3 tasks completed at every checkpoint"],
  [152, "The Table Set", "lab", 4, "A", "common", "checklist", "#FFF7ED", "#B45309", "A checklist with every item ticked - the setup confirmed before anything begins", "Nothing can begin until everything needed to begin is confirmed in place.", "Complete Task 1 of Checkpoint 1 in Stage 4 (Build & Execute) - confirm every item on your resources list and document substitutions"],
  [153, "The Run Complete", "lab", 4, "B", "rare", "flask", "#FCE7F3", "#9D174D", "A flask with its contents fully emptied - the experiment run to completion", "The Lab was not imagined. It was done.", "Complete Stage 4 (Build & Execute) on any Lab idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [154, "The Execution Perfect", "lab", 4, "C", "epic", "star_flask", "#FDE68A", "#92400E", "A flask with a gold star - the experiment run with documented evidence at every step", "Trial run documented. Adjustments locked. Full execution uploaded. Nothing improvised.", "Complete Stage 4 (Build & Execute) with all 3 tasks completed at every checkpoint"],
  [155, "The Output Laid Out", "lab", 5, "A", "common", "table", "#F0FDF4", "#059669", "A table with items laid out in order - raw results made visible and accessible", "Raw results are not findings. They become findings when someone organises them.", "Complete Task 1 of Checkpoint 1 in Stage 5 (Test & Evaluate) - describe every decision made in organising the raw output"],
  [156, "The Evidence Weighed", "lab", 5, "B", "rare", "scale", "#FCE7F3", "#9D174D", "A balance scale with results on one side and the hypothesis on the other - the judgment being made", "The hypothesis was a guess. The results are the answer.", "Complete Stage 5 (Test & Evaluate) on any Lab idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [157, "The Evaluation Complete", "lab", 5, "C", "epic", "crown_scale", "#FDE68A", "#92400E", "A crowned scale - the evaluation done with rigour and documented fully", "Organised output uploaded. Visualisation built. Limitations honest. Benchmarks compared.", "Complete Stage 5 (Test & Evaluate) with all 3 tasks completed at every checkpoint"],
  [158, "The Verdict Written", "lab", 6, "A", "common", "scroll", "#EEF2FF", "#4F46E5", "A scroll with a single bold line at the bottom - the conclusion stated clearly", "A conclusion not written is a conclusion not reached.", "Complete Task 1 of Checkpoint 1 in Stage 6 (Iterate & Refine) - write a one-paragraph conclusion citing the most important evidence"],
  [159, "The Loop Closed", "lab", 6, "B", "uncommon", "ring", "#EEEDFE", "#7F77DD", "A closed ring with a small arrow - the cycle of test, learn, refine completed", "The first run taught you something. You proved it by changing.", "Complete Stage 6 (Iterate & Refine) on any Lab idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [160, "The Cycle Mastered", "lab", 6, "C", "rare", "spiral", "#FDE68A", "#92400E", "An upward spiral - each loop higher than the last, the improvement visible in the shape", "Verdict written. Follow-up proposed. Refined version uploaded and compared.", "Complete Stage 6 (Iterate & Refine) with all 3 tasks completed at every checkpoint"],
  [161, "The Story Assembled", "lab", 7, "A", "common", "book_stack", "#FFF7ED", "#B45309", "A neat stack of pages - all sections gathered into a single ordered document", "A report is not a collection of sections. It is a single argument.", "Complete Task 1 of Checkpoint 1 in Stage 7 (Document & Present) - compile all sections into a single report with consistent structure"],
  [162, "The Record Sealed", "lab", 7, "B", "uncommon", "wax_seal", "#ECFDF5", "#059669", "A wax seal pressed onto a closed document - the final record complete and authenticated", "The Lab ended when the last page was finished. Not before.", "Complete Stage 7 (Document & Present) on any Lab idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [163, "The Lab Closed", "lab", 7, "C", "rare", "monument", "#FDE68A", "#92400E", "A small monument with a date carved into it - the Lab complete and permanently recorded", "Full report uploaded. Presentation run through. Every question answered.", "Complete Stage 7 (Document & Present) with all 3 tasks completed at every checkpoint"],
  [164, "The Feeling Admitted", "creative", 1, "A", "common", "spark", "#FDF4FF", "#9D174D", "A small unguarded flame - honest and unrefined, exactly as it first appeared", "Not polished. Not planned. Just honest.", "Complete Task 1 of Checkpoint 1 in Stage 1 (Concept & Inspiration) - describe the impulse or feeling driving the work"],
  [165, "The Impulse Named", "creative", 1, "B", "common", "lantern", "#FDF4FF", "#9D174D", "A lantern with a soft glow - the creative impulse held steady and given shape", "The feeling existed before the form. Now both exist.", "Complete Stage 1 (Concept & Inspiration) on any Creative idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [166, "The Concept Crystallised", "creative", 1, "C", "uncommon", "crystal", "#FDE68A", "#92400E", "A crystal with multiple clear facets - the concept defined from every angle", "Canvas mapped. Form defended. Artist's statement written as if the piece were finished.", "Complete Stage 1 (Concept & Inspiration) with all 3 tasks completed at every checkpoint"],
  [167, "The Relatives Named", "creative", 2, "A", "common", "tree", "#EEF2FF", "#4F46E5", "A small family tree - branches showing the lineage the work inherits from", "Every piece of work has ancestors. These are yours.", "Complete Task 1 of Checkpoint 1 in Stage 2 (References & Influences) - list at least six relevant works with a sentence on each"],
  [168, "The Lineage Traced", "creative", 2, "B", "common", "thread", "#FDF4FF", "#9D174D", "A thread connecting several points - the creative lineage made visible", "You know where you come from. Now you can decide where you go.", "Complete Stage 2 (References & Influences) on any Creative idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [169, "The Position Owned", "creative", 2, "C", "uncommon", "flag", "#FDE68A", "#92400E", "A flag planted between other flags - the creative position claimed deliberately", "Six influences linked. Three craft analyses written. The mood board built. The position defended.", "Complete Stage 2 (References & Influences) with all 3 tasks completed at every checkpoint"],
  [170, "The Frame Built", "creative", 3, "A", "common", "architecture", "#FFF7ED", "#B45309", "A frame without its painting - the structure ready for what will fill it", "Structure is not a cage. It is the skeleton that lets the work stand.", "Complete Task 1 of Checkpoint 1 in Stage 3 (Drafting & Creation) - map the structure of the piece on the canvas"],
  [171, "The Draft Lives", "creative", 3, "B", "uncommon", "scroll", "#FDF4FF", "#9D174D", "A half-unrolled scroll with visible writing - the draft in its first complete form", "It did not exist before. Now it does. That is everything.", "Complete Stage 3 (Drafting & Creation) on any Creative idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [172, "The Draft Whole", "creative", 3, "C", "rare", "gem", "#FDE68A", "#92400E", "A complete uncut gem - full of potential, the raw form of something exceptional", "Two alternative openings. Two alternative endings. The full draft shared. The concept revisited.", "Complete Stage 3 (Drafting & Creation) with all 3 tasks completed at every checkpoint"],
  [173, "The Door Opened", "creative", 4, "A", "common", "open_door", "#F0FDF4", "#059669", "A door ajar with light from the other side - the work made available to another", "The work was shared. That is an act of courage before it is anything else.", "Complete Task 1 of Checkpoint 1 in Stage 4 (Feedback & Critique) - confirm the draft was shared with at least one person"],
  [174, "The Other Eyes", "creative", 4, "B", "uncommon", "two_eyes", "#FDF4FF", "#9D174D", "Two eyes looking at a piece of work - external perspective brought to bear", "You stopped protecting it. You let someone else see it.", "Complete Stage 4 (Feedback & Critique) on any Creative idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [175, "The Critique Absorbed", "creative", 4, "C", "rare", "sponge", "#FDE68A", "#92400E", "A sponge taking in liquid - the capacity to receive without deflecting", "Two readers. Their differences documented. The hardest feedback accepted.", "Complete Stage 4 (Feedback & Critique) with all 3 tasks completed at every checkpoint"],
  [176, "The Cuts Decided", "creative", 5, "A", "common", "scissors", "#EEF2FF", "#4F46E5", "A pair of scissors open - ready to remove what does not belong", "Knowing what to change is the beginning of knowing what the piece actually is.", "Complete Task 1 of Checkpoint 1 in Stage 5 (Refinement & Polish) - write a revision list of at least five changes ordered from structural to detail"],
  [177, "The Final Form", "creative", 5, "B", "rare", "diamond", "#FCE7F3", "#9D174D", "A cut diamond - the same material as the rough stone, transformed by deliberate attention", "The version that remained after everything unnecessary was removed.", "Complete Stage 5 (Refinement & Polish) on any Creative idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [178, "The Polish Complete", "creative", 5, "C", "epic", "star_diamond", "#FDE68A", "#92400E", "A diamond with a star - not just cut, but exceptional in the cutting", "Structural changes logged. Three weakest moments rewritten. The piece performed aloud.", "Complete Stage 5 (Refinement & Polish) with all 3 tasks completed at every checkpoint"],
  [179, "The Package Sealed", "creative", 6, "A", "common", "envelope", "#FFF7ED", "#B45309", "A sealed envelope - the piece ready for delivery, the flap pressed shut", "The form the audience receives is itself a creative decision.", "Complete Task 1 of Checkpoint 1 in Stage 6 (Release & Sharing) - upload the piece in its release format"],
  [180, "The Work Released", "creative", 6, "B", "rare", "open_hand", "#FCE7F3", "#9D174D", "An open hand releasing something upward - the work let go into the world", "It no longer belongs only to you. It belongs to everyone who encounters it.", "Complete Stage 6 (Release & Sharing) on any Creative idea - advance through all checkpoints by completing any 2 of 3 tasks each"],
  [181, "The Release Mastered", "creative", 6, "C", "epic", "torch", "#FDE68A", "#92400E", "A raised torch - the work shared with full intention, the light deliberately passed on", "Two release formats. Ten people actively reached. The release reflected on.", "Complete Stage 6 (Release & Sharing) with all 3 tasks completed at every checkpoint"],
];

export const STAGE_BADGE_DEFINITIONS: StageBadgeDef[] = rows.map(
  ([
    id,
    name,
    template,
    stage,
    badgeType,
    rarity,
    shape,
    primaryColor,
    secondaryColor,
    iconDescription,
    tagline,
    requirement,
  ]) => ({
    id,
    name,
    template,
    stage,
    badgeType,
    category: "idea_milestones",
    rarity,
    shape,
    primaryColor,
    secondaryColor,
    iconDescription,
    tagline,
    requirement,
  }),
);

export const STAGE_BADGE_IDS = new Set(
  STAGE_BADGE_DEFINITIONS.map((badge) => badge.id),
);

export const LEGACY_STAGE_BADGE_IDS = new Set([
  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
  71, 72, 73, 74, 75, 76, 77, 78,
]);

export const LEGACY_STAGE_BADGE_EQUIVALENTS = new Map<number, number>([
  [9, 101],
  [10, 103],
  [11, 102],
  [12, 108],
  [13, 114],
  [14, 117],
  [15, 123],
  [16, 124],
  [17, 141],
  [18, 162],
  [19, 180],
  [20, 123],
  [71, 102],
  [72, 105],
  [73, 108],
  [74, 111],
  [75, 114],
  [76, 117],
  [77, 120],
  [78, 123],
]);
